Repository anagrambuild/bonsol, pull requests merged in 2024-10, with the labels that each got.

#20 Add `simple` e2e test; package `solana-cli:v1.18.22` and scripts
  .gitignore
  README.md
  cli/src/build.rs
  cli/src/deploy.rs
  docs/docs/contributing/contributing.md
  flake.nix
  nixos/pkgs/bonsol/run-relay.nix
  nixos/pkgs/bonsol/setup.nix
  nixos/pkgs/bonsol/validator.nix
  nixos/pkgs/risc0/mkRisc0Package.nix
  nixos/pkgs/solana/default.nix
  nixos/pkgs/solana/patches/v1.18.22/cargo-build-sbf.diff
  nixos/pkgs/solana/platform-tools/default.nix
  pnpm-lock.yaml
  relay/Cargo.toml
  relay/NodeDocker.toml
  run-relay.sh
  validator.sh
  vkey/package.json
Labels: enhancement

#46 add preliminary support for code spaces
  .devcontainer/devcontainer.json
  .github/dependabot.yml
  .vscode/tasks.json
  Dockerfile
Labels: enhancement

#47 chore: Create unit tests for dragon ingester
  Cargo.lock
  node/Cargo.toml
  node/src/ingest/dragon.rs
  node/src/types.rs
Labels: enhancement

#64 fix: Fix non-determinism in dragon ingester test
  node/src/ingest/dragon.rs
Labels: bug

#61 feat: Add derivation for `risc0-groth16-prover` binaries
  .github/workflows/ci.yaml
  CHANGELOG.md
  docs/docs/contributing/contributing.md
  flake.nix
  nixos/pkgs/risc0/groth16-prover/default.nix
  pnpm-workspace.yaml
  setup.dockerfile
Labels: enhancement

#80 docs: setup cleanup
  bin/setup.sh
  docs/docs/contributing/contributing.mdx
Labels: documentation

#75 chore: Automatically update binary cache
  .github/workflows/update-cachix.yml
Labels: enhancement

#86 chore: yamlfmt
  .github/workflows/update-cachix.yml
Labels: build
